on:
  push:
    branches:
        - githubaction-sync-fork
  schedule:
    - cron:  '0 7 * * 1-5'
    # scheduled at 07:00 every weekday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: ArmDeveloperEcosystem/arm-learning-paths
        upstream_branch: main
        target_branch: main
        git_pull_args: --rebase

        # Set test_mode true to run tests instead of the true action!
        test_mode: true

    - name: Timestamp
      run: date
