name: Test Learning Path
on: pull_request
jobs:
  Test-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.md
      - name: Install dependencies
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: pip install -r tools/requirements.txt

      - name: Run test suite for all changed files
        id: run-suite
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        # Run the test suite, and then determine if maintenance is turned off
        run: |
            ./.github/workflows/test_lp.sh ${{ steps.changed-markdown-files.outputs.all_changed_files }}
            ./.github/workflows/test_lp.sh ${{ steps.changed-markdown-files.outputs.all_changed_files }} 1>/dev/null \
            | grep -q 'maintenance is turned off' && echo "{MAINTENANCE}=off" >> "$GITHUB_ENV" \
            || echo "{MAINTENANCE}=on" >> "$GITHUB_ENV"
      - name: Test condition
        if: success() && steps.run-suite.outputs.MAINTENANCE == 'off'
        # Skip opening a PR if nothing has changed
        run: echo "Maintenance is turned off for one or more files, skipping tests"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: success() && steps.run-suite.outputs.MAINTENANCE == 'on'
        with:
          commit-message: update stats_current_test_info.yml
          title: Update stats_current_test_info.yml
          body: |
            Update test result file with recent run
            Auto-generated by create-pull-request: https://github.com/peter-evans/create-pull-request
          branch: update-stats
          base: main